Django/sena/sena/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('tienda.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/sena/tienda/urls.py
from django.urls import path

from . import views

app_name = "tienda"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("productos/", views.productos, name="productos"),
    path("listar_categorias/", views.categorias, name="listar_categorias"),
    path("form_cat/", views.categorias_crear_formulario, name="form_cat"),
    path("categorias_guardar/", views.categorias_guardar, name="categorias_guardar"),
    path("form_edit_cat/<int:id>/", views.categorias_editar_formulario, name="form_edit_cat"),
    path("categoria_eliminar/<int:id>/", views.categoria_eliminar, name="categoria_eliminar"),
    path("cat_buscar/", views.cat_buscar, name="cat_buscar"),
    path("form_pro/", views.productos_crear_formulario, name="form_pro"),
    path("productos_guardar", views.productos_guardar, name="productos_guardar"),
    path("productos_eliminar/<int:id>/", views.productos_eliminar, name="productos_eliminar"),
    path("productos_editar/<int:id>/", views.productos_editar, name="productos_editar"),
    path("cambiar_clave/", views.cambiar_clave, name="cambiar_clave"),
    path("guardar_clave/", views.guardar_clave, name="guardar_clave"),
    path("perfil/", views.ver_perfil, name="perfil"),

    # Carrito de compra...
    path("carrito_agregar/", views.carrito_agregar, name="carrito_agregar"),
    path("carrito_listar/", views.carrito_listar, name="carrito_listar"),
    path("carrito_eliminar/<int:id>", views.carrito_eliminar, name="carrito_eliminar"),
    path("carrito_actualizar", views.carrito_actualizar, name="carrito_actualizar"),
    path("establecer_venta", views.establecer_venta, name="establecer_venta"),

    path("ventas/", views.ventas, name="venta"),
    path("ventas_usuario/", views.venta_usuario, name="venta_usuario"),
    path("detalleVenta_usuario/<int:id>", views.detalle_venta_usuarios, name="detalleVenta_usuario")
]

Django/sena/tienda/models.py
from django.db import models


# Create your models here.


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.id} ----- {self.nombre}"


class Producto(models.Model):
    nombre = models.CharField(max_length=254)
    precio = models.IntegerField()
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    fecha_compra = models.DateField()
    stock = models.IntegerField(default=1)
    foto = models.ImageField(null=True, blank=True, default='fotos_productos/default.png', upload_to='fotos_productos')

    def __str__(self):
        return f"{self.id} ----- {self.nombre} ----- {self.precio}"


class Usuarios(models.Model):
    ROLES = (
        (1, 'Administrador'),
        (2, 'WebMaster'),
        (3, 'Usuario'),
    )
    foto = models.ImageField(null=True, blank=True, default='fotos/default.png', upload_to='fotos')
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    userName = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)
    rol = models.IntegerField(choices=ROLES, default=3)

    def __str__(self):
        return f"{self.userName}"


class Venta(models.Model):
    fecha_venta = models.DateField(auto_now=True)
    usuario = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING)
    ESTADOS = (
        (1, 'Pendiente'),
        (2, 'Enviado'),
        (3, 'Rechazado'),
    )
    estado = models.IntegerField(choices=ESTADOS, default=1)

    def __str__(self):
        return f"{self.id} - {self.usuario}"


class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
    cantidad = models.IntegerField()
    precio_historico = models.IntegerField()

    def __str__(self):
        return f"{self.id} - {self.venta}"

Django/sena/tienda/views.py
import requests
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from django.contrib import messages

from .models import *

from django.db import IntegrityError, transaction


# Create your views here.


def login(request):
    if request.method == "POST":
        userName = request.POST.get("userName")
        password = request.POST.get("password")
        try:
            q = Usuarios.objects.get(userName=userName, password=password)
            messages.success(request, "Bienvenido!!")
            datos = {
                "rol": q.rol,
                "nombre_rol": q.get_rol_display(),
                "nombre": f"{q.nombre} {q.apellido}",
                "foto": q.foto.url if q.foto else "media/fotos/default.png",
                "id": q.id
            }
            request.session["logueo"] = datos
            request.session["carrito"] = []
            request.session["cantidad_productos"] = 0
            return HttpResponseRedirect(reverse("tienda:index"))

        except Usuarios.DoesNotExist:
            messages.error(request, "Usuario o contraseña no validos")
            return render(request, "tienda/login.html")
    else:
        if request.session.get("logueo", False):
            return HttpResponseRedirect(reverse("tienda:index"))
        else:
            return render(request, "tienda/login.html")


def logout(request):
    try:
        del request.session["logueo"]
        del request.session["carrito"]
        del request.session["cantidad_productos"]
        messages.success(request, "Sesion cerrada correctamente")
    except Exception as e:
        messages.error(request, f"Error: {e}")
    return HttpResponseRedirect(reverse("tienda:login"))


def index(request):
    if request.session.get("logueo", False):
        c = Categoria.objects.all()

        # Detectar si viene paramétro id categoría para filtrar o no...
        filtro_categoria = request.GET.get("id")

        if filtro_categoria != None and filtro_categoria != '0':
            p = Producto.objects.filter(categoria_id=filtro_categoria)
            request.session["submenu"] = int(filtro_categoria)
        else:
            p = Producto.objects.all()
            request.session["submenu"] = 0

        contexto = {"categorias": c, "productos": p}
        return render(request, "tienda/index.html", contexto)
    else:
        return HttpResponseRedirect(reverse("tienda:login"))


def categorias(request):
    sesion = request.session.get("logueo", False)
    if sesion["nombre_rol"] != "Usuario":
        result = Categoria.objects.all()
        context = {"data": result}
        return render(request, "tienda/categoria/listar.html", context)
    else:
        messages.warning(request, "Te crees hacker e intentas eso, sos un pequeñin")
        return HttpResponseRedirect(reverse("tienda:index"))


def categorias_crear_formulario(request):
    return render(request, "tienda/categoria/cat-form.html")


def categorias_guardar(request):
    if request.method == "POST":
        nomb = request.POST.get("nombre")
        desc = request.POST.get("descripcion")
        # insert into categoria values (null, nomb, desc)
        try:
            cat = Categoria(
                nombre=nomb,
                descripcion=desc
            )
            cat.save()
            messages.success(request, "Los datos fueron guardados correctamente")
        except Exception as e:
            messages.error(request, f"Error {e}")

        return HttpResponseRedirect(reverse("tienda:listar_categorias", args=()))
    else:
        messages.error(request, "No se enviaron datos...")
        return HttpResponseRedirect(reverse("tienda:form_cat", args=()))


def categorias_editar_formulario(request, id):
    q = Categoria.objects.get(pk=id)
    contexto = {"id": id, "data": q}
    return render(request, "tienda/categoria/cat-form.html", contexto)


def categoria_eliminar(request):
    return render(request, "tienda/categoria_eliminar")


def cat_buscar(request):
    render(request, "")


def productos(request):
    query = Producto.objects.all()
    contexto = {"data": query}
    return render(request, "tienda/productos/listar.html", contexto)


def productos_crear_formulario(request):
    query = Categoria.objects.all()
    contexto = {"categorias": query}
    return render(request, "tienda/productos/form_pro.html", contexto)


def productos_guardar(request):
    if request.method == "POST":
        nomb = request.POST.get("nombre")
        pre = request.POST.get("precio")
        fech = request.POST.get("fecha_compra")
        cat = Categoria.objects.get(pk=request.POST.get("categoria"))

        # insert into categoria values (null, nomb, desc)
        try:
            pro = Producto(
                nombre=nomb,
                precio=pre,
                fecha_compra=fech,
                categoria=cat
            )
            pro.save()
            messages.success(request, "Los datos fueron guardados correctamente")
        except Exception as e:
            messages.error(request, f"Error {e}")

        return HttpResponseRedirect(reverse("tienda:productos", args=()))
    else:
        try:
            q = Producto.objects.get(pk=id)
            q.nombre = nomb
            q.precio = pre
            q.fecha_compra = fech
            q.categoria = cat
            q.save()
            messages.success(request, "Actualizacion correcta")
        except Exception as e:
            messages.error(request, f"Error {e}")

    return HttpResponseRedirect(reverse("tienda:form_pro", args=()))


def productos_eliminar(request, id):
    try:
        q = Producto.objects.get(pk=id)
        q.delete()
        messages.success(request, "Registro eliminado")
    except Exception as e:
        messages.error(request, "Errror {e}")
    return HttpResponseRedirect(reverse("tienda:productos", args=()))


def productos_editar(request, id):
    q = Producto.objects.get(pk=id)
    query = Categoria.objects.all()
    contexto = {"id": id, "data": q, "categorias": query}
    return render(request, "tienda/productos/form_pro.html", contexto)


def cambiar_clave(request):
    return render(request, "tienda/usuarios/cambio_clave.html")


def guardar_clave(request):
    usuario = request.session.get("logueo", False)
    if usuario:
        if request.method == "POST":
            actual = request.POST.get("actual")
            clave1 = request.POST.get("clave1")
            clave2 = request.POST.get("clave2")
            try:
                q = Usuarios.objects.get(pk=usuario["id"], password=actual)
                if clave1 == clave2:
                    q.password = clave1
                    q.save()
                    messages.success(request, "Contraseña cambiada correctamente")
                    return HttpResponseRedirect(reverse("tienda:cambiar_clave"))
                else:
                    messages.warning(request, "Nuevas contraseñas no coinciden")
                    return HttpResponseRedirect(reverse("tienda:cambiar_clave", kwargs={'actual': actual}))
            except Exception as e:
                messages.warning(request, "Contraseña no valida...")
                return HttpResponseRedirect(reverse("tienda:cambiar_clave"))
    else:
        return HttpResponseRedirect(reverse("tienda:logueo"))


def ver_perfil(request):
    usuario = request.session.get("logueo", False)
    q = Usuarios.objects.get(pk=usuario["id"])
    contexto = {"data": q}
    return render(request, "tienda/usuarios/perfil.html", contexto)


def carrito_agregar(request):
    if request.method == "POST":
        id_producto = request.POST.get("id")
        cantidad = int(request.POST.get("cantidad"))

        if not request.session.get("carrito", False):
            request.session["carrito"] = []
            request.session["cantidad_productos"] = 0

        carrito = request.session.get("carrito", False)

        pro = Producto.objects.get(pk=id_producto)

        encontrado = False
        for p in carrito:
            if p["id"] == id_producto:
                encontrado = True
                if cantidad > 0 and p["cantidad"] + cantidad <= pro.stock:
                    p["cantidad"] += cantidad
                    messages.success(request, "Producto ya en carrito, se incremeto la cantidad!")
                else:
                    messages.warning(request, "La cantidad supera el Stock")
                break
        if not encontrado:
            if cantidad > 0 and cantidad <= pro.stock:
                carrito.append({"id": id_producto, "cantidad": cantidad})
                messages.success(request, "Producto agregado")
            else:
                messages.warning(request, "La cantidad supera el Stock")

        request.session["carrito"] = carrito
        request.session["cantidad_productos"] = len(request.session["carrito"])
        print(carrito)

    else:
        messages.warning(request, "No se enviaron datos...")
    return redirect("tienda:index")


def carrito_listar(request):
    carrito = request.session.get("carrito", False)

    if carrito is not False:
        total = 0
        print()
        try:
            for indice, p in enumerate(carrito):
                query = Producto.objects.get(pk=p["id"])
                p["nombre"] = query.nombre
                p["precio"] = query.precio
                p["foto"] = query.foto.url
                p["subtotal"] = p["cantidad"] * query.precio
                total += p["subtotal"]
        except Producto.DoesNotExist:
            carrito.pop(indice)
            request.session["carrito"] = carrito

    contexto = {"datos": carrito, "total": total}

    return render(request, "tienda/carrito/listar_carrito.html", contexto)


def carrito_eliminar(request, id):
    if request.method == "GET":
        id_producto = request.GET.get("id")
        carrito = request.session.get("carrito", False)

        if carrito:

Django/sena/tienda/templates/tienda/ventas/listar_detalleVenta_usuarios.html
{% extends 'tienda/base.html' %}

{% load static %}

{% block titul %} Ventas {% endblock %}

{% block contenedor %}
    <br>
    {% if data %}
        <table class="table table-hover">
            <tr>
                <th>Venta</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Precio Historico</th>
                <!-- <th>Subtotal</th> -->
            </tr>
        {% for v in data %}
            <tr>
                <td>{{ v.venta }} </td>
                <td>{{v.producto}} </td>
                <td>{{v.cantidad}}</td>
                <td>{{v.precio_historico}}</td>
                <!-- <td>{{v.subtotal}}</td> -->
            </tr>
        {% endfor %}
        </table>
    {% else %}
        NO hay registros...
    {% endif %}
{% endblock %}

Django/sena/tienda/templates/tienda/ventas/listar_ventas_admin.html
{% extends 'tienda/base.html' %}

{% load static %}

{% block titul %} Ventas {% endblock %}

{% block contenedor %}
    <br>
    <form class="form-inline" role="search" method="post" action="#">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar por nombre o descripcion" aria-label="Search" name="buscar" value="{{buscado}}">
        <button class="btn btn-outline-success my-2 my-ms-0" type="submit">Buscar</button><br>
    </form>
    {% if data %}
        <table class="table table-hover">
            <tr>
                <th>Venta</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Precio Historico</th>
                <th>Acciones</th>
                <!-- <th>Subtotal</th> -->
            </tr>
        {% for v in data %}
            <tr>
                <td>{{ v.venta }} </td>
                <td>{{v.producto}} </td>
                <td>{{v.cantidad}}</td>
                <td>{{v.precio_historico}}</td>
                <!-- <td>{{v.subtotal}}</td> -->
                <td>
                    <a href="#" class="btn btn-info">Editar</a>
                    <button class="btn btn-danger">Eliminar</button>
                </td>
            </tr>
        {% endfor %}
        </table>
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
          </ul>
        </nav>
    {% else %}
        NO hay registros...
    {% endif %}
{% endblock %}

Django/sena/tienda/templates/tienda/ventas/listar_ventas_usuarios.html
{% extends 'tienda/base.html' %}

{% load static %}

{% block titul %} Ventas {% endblock %}

{% block contenedor %}
    <br>
    <form class="form-inline" role="search" method="post" action="#">
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar por nombre o descripcion" aria-label="Search" name="buscar" value="{{buscado}}">
        <button class="btn btn-outline-success my-2 my-ms-0" type="submit">Buscar</button><br>
    </form>
    {% if data %}
        <table class="table table-hover">
            <tr>
                <th>ID</th>
                <th>Fecha Venta</th>
                <th>Estado</th>
                <th>Acciones</th>
                <!-- <th>Subtotal</th> -->
            </tr>
        {% for v in data %}
            <tr>
                <td>{{ v.id }} </td>
                <td>{{v.fecha_venta}} </td>
                <td>{{v.estado}}</td>
                <!-- <td>{{v.subtotal}}</td> -->
                <td>
                    <a href="{% url 'tienda:detalleVenta_usuario' v.id %}" class="btn btn-success"><i class="bi bi-eye-fill"></i></a>
                </td>
            </tr>
        {% endfor %}
        </table>
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
          </ul>
        </nav>
    {% else %}
        NO hay registros...
    {% endif %}
{% endblock %}