Django/sena/sena/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('tienda.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/sena/tienda/urls.py
from django.urls import path

from . import views

app_name = "tienda"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("productos/", views.productos, name="productos"),
    path("listar_categorias/", views.categorias, name="listar_categorias"),
    path("form_cat/", views.categorias_crear_formulario, name="form_cat"),
    path("categorias_guardar/", views.categorias_guardar, name="categorias_guardar"),
    path("form_edit_cat/<int:id>/", views.categorias_editar_formulario, name="form_edit_cat"),
    path("categoria_eliminar/<int:id>/", views.categoria_eliminar, name="categoria_eliminar"),
    path("cat_buscar/", views.cat_buscar, name="cat_buscar"),
    path("form_pro/", views.productos_crear_formulario, name="form_pro"),
    path("productos_guardar", views.productos_guardar, name="productos_guardar"),
    path("productos_eliminar/<int:id>/", views.productos_eliminar, name="productos_eliminar"),
    path("productos_editar/<int:id>/", views.productos_editar, name="productos_editar"),
    path("cambiar_clave/", views.cambiar_clave, name="cambiar_clave"),
    path("guardar_clave/", views.guardar_clave, name="guardar_clave"),
    path("perfil/", views.ver_perfil, name="perfil"),

    # Carrito de compra...
    path("carrito_agregar/", views.carrito_agregar, name="carrito_agregar"),
    path("carrito_listar/", views.carrito_listar, name="carrito_listar"),
    path("carrito_eliminar/<int:id>", views.carrito_eliminar, name="carrito_eliminar"),
    path("carrito_actualizar", views.carrito_actualizar, name="carrito_actualizar"),
    path("establecer_venta", views.establecer_venta, name="establecer_venta"),

    path("ventas/", views.ventas, name="venta"),
    path("ventas_usuario/", views.venta_usuario, name="venta_usuario"),
    path("detalleVenta_usuario/<int:id>", views.detalle_venta_usuarios, name="detalleVenta_usuario")
]

Django/sena/tienda/models.py
from django.db import models


# Create your models here.


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.id} ----- {self.nombre}"


class Producto(models.Model):
    nombre = models.CharField(max_length=254)
    precio = models.IntegerField()
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    fecha_compra = models.DateField()
    stock = models.IntegerField(default=1)
    foto = models.ImageField(null=True, blank=True, default='fotos_productos/default.png', upload_to='fotos_productos')

    def __str__(self):
        return f"{self.id} ----- {self.nombre} ----- {self.precio}"


class Usuarios(models.Model):
    ROLES = (
        (1, 'Administrador'),
        (2, 'WebMaster'),
        (3, 'Usuario'),
    )
    foto = models.ImageField(null=True, blank=True, default='fotos/default.png', upload_to='fotos')
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    userName = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)
    rol = models.IntegerField(choices=ROLES, default=3)

    def __str__(self):
        return f"{self.userName}"


class Venta(models.Model):
    fecha_venta = models.DateField(auto_now=True)
    usuario = models.ForeignKey(Usuarios, on_delete=models.DO_NOTHING)
    ESTADOS = (
        (1, 'Pendiente'),
        (2, 'Enviado'),
        (3, 'Rechazado'),
    )
    estado = models.IntegerField(choices=ESTADOS, default=1)

    def __str__(self):
        return f"{self.id} - {self.usuario}"


class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
    cantidad = models.IntegerField()
    precio_historico = models.IntegerField()

    def __str__(self):
        return f"{self.id} - {self.venta}"

Django/sena/tienda/views.py
import requests
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from django.contrib import messages

from .models import *

from django.db import IntegrityError, transaction


# Create your views here.


def login(request):
    if request.method == "POST":
        userName = request.POST.get("userName")
        password = request.POST.get("password")
        try:
            q = Usuarios.objects.get(userName=userName, password=password)
            messages.success(request, "Bienvenido!!")
            datos = {
                "rol": q.rol,
                "nombre_rol": q.get_rol_display(),
                "nombre": f"{q.nombre} {q.apellido}",
                "foto": q.foto.url if q.foto else "media/fotos/default.png",
                "id": q.id
            }
            request.session["logueo"] = datos
            request.session["carrito"] = []
            request.session["cantidad_productos"] = 0
            return HttpResponseRedirect(reverse("tienda:index"))

        except Usuarios.DoesNotExist:
            messages.error(request, "Usuario o contraseña no validos")
            return render(request, "tienda/login.html")
    else:
        if request.session.get("logueo", False):
            return HttpResponseRedirect(reverse("tienda:index"))
        else:
            return render(request, "tienda/login.html")


def logout(request):
    try:
        del request.session["logueo"]
        del request.session["carrito"]
        del request.session["cantidad_productos"]
        messages.success(request, "Sesion cerrada correctamente")
    except Exception as e:
        messages.error(request, f"Error: {e}")
    return HttpResponseRedirect(reverse("tienda:login"))


def index(request):
    if request.session.get("logueo", False):
        c = Categoria.objects.all()

        # Detectar si viene paramétro id categoría para filtrar o no...
        filtro_categoria = request.GET.get("id")

        if filtro_categoria != None and filtro_categoria != '0':
            p = Producto.objects.filter(categoria_id=filtro_categoria)
            request.session["submenu"] = int(filtro_categoria)
        else:
            p = Producto.objects.all()
            request.session["submenu"] = 0

        contexto = {"categorias": c, "productos": p}
        return render(request, "tienda/index.html", contexto)
    else:
        return HttpResponseRedirect(reverse("tienda:login"))


def categorias(request):
    sesion = request.session.get("logueo", False)
    if sesion["nombre_rol"] != "Usuario":
        result = Categoria.objects.all()
        context = {"data": result}
        return render(request, "tienda/categoria/listar.html", context)
    else:
        messages.warning(request, "Te crees hacker e intentas eso, sos un pequeñin")
        return HttpResponseRedirect(reverse("tienda:index"))


def categorias_crear_formulario(request):
    return render(request, "tienda/categoria/cat-form.html")


def categorias_guardar(request):
    if request.method == "POST":
        nomb = request.POST.get("nombre")
        desc = request.POST.get("descripcion")
        # insert into categoria values (null, nomb, desc)
        try:
            cat = Categoria(
                nombre=nomb,
                descripcion=desc
            )
            cat.save()
            messages.success(request, "Los datos fueron guardados correctamente")
        except Exception as e:
            messages.error(request, f"Error {e}")

        return HttpResponseRedirect(reverse("tienda:listar_categorias", args=()))
    else:
        messages.error(request, "No se enviaron datos...")
        return HttpResponseRedirect(reverse("tienda:form_cat", args=()))


def categorias_editar_formulario(request, id):
    q = Categoria.objects.get(pk=id)
    contexto = {"id": id, "data": q}
    return render(request, "tienda/categoria/cat-form.html", contexto)


def categoria_eliminar(request):
    return render(request, "tienda/categoria_eliminar")


def cat_buscar(request):
    render(request, "")


def productos(request):
    query = Producto.objects.all()
    contexto = {"data": query}
    return render(request, "tienda/productos/listar.html", contexto)


def productos_crear_formulario(request):
    query = Categoria.objects.all()
    contexto = {"categorias": query}
    return render(request, "tienda/productos/form_pro.html", contexto)


def productos_guardar(request):
    if request.method == "POST":
        nomb = request.POST.get("nombre")
        pre = request.POST.get("precio")
        fech = request.POST.get("fecha_compra")
        cat = Categoria.objects.get(pk=request.POST.get("categoria"))

        # insert into categoria values (null, nomb, desc)
        try:
            pro = Producto(
                nombre=nomb,
                precio=pre,
                fecha_compra=fech,
                categoria=cat
            )
            pro.save()
            messages.success(request, "Los datos fueron guardados correctamente")
        except Exception as e:
            messages.error(request, f"Error {e}")

        return HttpResponseRedirect(reverse("tienda:productos", args=()))
    else:
        try:
            q = Producto.objects.get(pk=id)
            q.nombre = nomb
            q.precio = pre
            q.fecha_compra = fech
            q.categoria = cat
            q.save()
            messages.success(request, "Actualizacion correcta")
        except Exception as e:
            messages.error(request, f"Error {e}")

    return HttpResponseRedirect(reverse("tienda:form_pro", args=()))


def productos_eliminar(request, id):
    try:
        q = Producto.objects.get(pk=id)
        q.delete()
        messages.success(request, "Registro eliminado")
    except Exception as e:
        messages.error(request, "Errror {e}")
    return HttpResponseRedirect(reverse("tienda:productos", args=()))


def productos_editar(request, id):
    q = Producto.objects.get(pk=id)
    query = Categoria.objects.all()
    contexto = {"id": id, "data": q, "categorias": query}
    return render(request, "tienda/productos/form_pro.html", contexto)


def cambiar_clave(request):
    return render(request, "tienda/usuarios/cambio_clave.html")


def guardar_clave(request):
    usuario = request.session.get("logueo", False)
    if usuario:
        if request.method == "POST":
            actual = request.POST.get("actual")
            clave1 = request.POST.get("clave1")
            clave2 = request.POST.get("clave2")
            try:
                q = Usuarios.objects.get(pk=usuario["id"], password=actual)
                if clave1 == clave2:
                    q.password = clave1
                    q.save()
                    messages.success(request, "Contraseña cambiada correctamente")
                    return HttpResponseRedirect(reverse("tienda:cambiar_clave"))
                else:
                    messages.warning(request, "Nuevas contraseñas no coinciden")
                    return HttpResponseRedirect(reverse("tienda:cambiar_clave", kwargs={'actual': actual}))
            except Exception as e:
                messages.warning(request, "Contraseña no valida...")
                return HttpResponseRedirect(reverse("tienda:cambiar_clave"))
    else:
        return HttpResponseRedirect(reverse("tienda:logueo"))


def ver_perfil(request):
    usuario = request.session.get("logueo", False)
    q = Usuarios.objects.get(pk=usuario["id"])
    contexto = {"data": q}
    return render(request, "tienda/usuarios/perfil.html", contexto)


def carrito_agregar(request):
    if request.method == "POST":
        id_producto = request.POST.get("id")
        cantidad = int(request.POST.get("cantidad"))

        if not request.session.get("carrito", False):
            request.session["carrito"] = []
            request.session["cantidad_productos"] = 0

        carrito = request.session.get("carrito", False)

        pro = Producto.objects.get(pk=id_producto)

        encontrado = False
        for p in carrito:
            if p["id"] == id_producto:
                encontrado = True
                if cantidad > 0 and p["cantidad"] + cantidad <= pro.stock:
                    p["cantidad"] += cantidad
                    messages.success(request, "Producto ya en carrito, se incremeto la cantidad!")
                else:
                    messages.warning(request, "La cantidad supera el Stock")
                break
        if not encontrado:
            if cantidad > 0 and cantidad <= pro.stock:
                carrito.append({"id": id_producto, "cantidad": cantidad})
                messages.success(request, "Producto agregado")
            else:
                messages.warning(request, "La cantidad supera el Stock")

        request.session["carrito"] = carrito
        request.session["cantidad_productos"] = len(request.session["carrito"])
        print(carrito)

    else:
        messages.warning(request, "No se enviaron datos...")
    return redirect("tienda:index")


def carrito_listar(request):
    carrito = request.session.get("carrito", False)

    if carrito is not False:
        total = 0
        print()
        try:
            for indice, p in enumerate(carrito):
                query = Producto.objects.get(pk=p["id"])
                p["nombre"] = query.nombre
                p["precio"] = query.precio
                p["foto"] = query.foto.url
                p["subtotal"] = p["cantidad"] * query.precio
                total += p["subtotal"]
        except Producto.DoesNotExist:
            carrito.pop(indice)
            request.session["carrito"] = carrito

    contexto = {"datos": carrito, "total": total}

    return render(request, "tienda/carrito/listar_carrito.html", contexto)


def carrito_eliminar(request, id):
    if request.method == "GET":
        id_producto = request.GET.get("id")
        carrito = request.session.get("carrito", False)

        if carrito:

Django/sena/tienda/templates/tienda/base.html
    {% load static %}
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Tienda SENA - {% block titul %}{% endblock %}</title>

        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'tienda/favicon_io/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'tienda/favicon_io/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'tienda/favicon_io/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'tienda/favicon_io/site.webmanifest' %}">

        <link rel="stylesheet" href="{% static 'tienda/css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'tienda/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'tienda:index' %}">Tienda</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'tienda:index' %}">Home</a>
                        </li>
                        {% if request.session.logueo.nombre_rol != "Usuario" %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'tienda:listar_categorias' %}">Categorias</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'tienda:venta' %}" class="nav-link">Ventas</a>
                            </li>
                        {% endif %}
                        {% if request.session.logueo.nombre_rol == "Usuario" %}
                            <li class="nav-item">
                                <a href="{% url 'tienda:venta_usuario' %}" class="nav-link">Ventas</a>
                            </li>
                        {% endif %}
                        <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Productos
                          </a>
                          <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'tienda:productos' %}">Listar</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Vender</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Revisar inventario</a></li>
                          </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'tienda:logout' %}">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'tienda:listar_categorias' %}" class="nav-link {% if request.session.logueo.nombre_rol == "Usuario" %} disabled {% endif %}" aria-disabled="true">Categorias(copia)</a>
                        </li>
                    </ul>
                    <div class="navbar-text">
                        {% if request.session.logueo %}
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    Bienvenido, {{ request.session.logueo.nombre }} ({{ request.session.logueo.nombre_rol }})
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'tienda:perfil' %}">Perfil</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'tienda:cambiar_clave' %}">Cambiar Contraseña</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>

                                    <li><a class="dropdown-item" href="{% url 'tienda:logout' %}">Cerrar sesión</a></li>
                                </ul>
                            </li>
                        </ul>
                        {% endif %}
                    </div>
                    {% if request.session.carrito %}
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <button class="btn btn-outline-secondary me-2 ms-2 position-relative" type="button" aria-controls="offcanvasRight" onclick="ver_carrito(`{% url 'tienda:carrito_listar' %}`)">
                                      <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-dark">
                                        {{ request.session.cantidad_productos }}
                                      </span>
                                      <span class="visually-hidden">Productos</span>
                                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                                          <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
                                      </svg>
                                    </button>
                                </li>
                            </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% if messages %}
            {% for message in messages %}

                <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible" role="alert">
                    <div>{{ message }}</div>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>

            {% endfor %}
        {% endif %}
        {% block contenedor %}

        {% endblock %}

        <footer class="fixed-bottom">
            Copyright - Colombia 2023
        </footer>

        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasRightLabel">Carrito de Compras</h5>
              <span id="loading_cc" class="d-none">
                  <div class="spinner-border text-secondary" role="status">
                      <span class="visually-hidden">Loading...</span>
                  </div>
              </span>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body" id="respuesta_carrito">
              <div class="spinner-border text-dark" role="status">
                  <span class="visually-hidden">Loading...</span>
              </div>
          </div>
            <hr>
          <div class="offcanvas-footer mb-3 ms-3">
              <a href="{% url 'tienda:establecer_venta' %}" class="btn btn-outline-info">Pagar</a>
              <a href="{% url 'tienda:carrito_eliminar' 0 %}" class="btn btn-outline-danger">Limpiar</a>
          </div>
        </div>

        <!-- JS include here -->
        <script src="{% static 'tienda/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'tienda/js/jquery-3.7.1.min.js' %}"></script>
        <script src="{% static 'tienda/js/library.js' %}"></script>
        <!-- fin - JS include -->
    </body>
    </html>

Django/sena/tienda/templates/tienda/base2.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tienda SENA - {% block titul %}{% endblock %}</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'tienda/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'tienda/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'tienda/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'tienda/favicon_io/site.webmanifest' %}">

    <link rel="stylesheet" href="{% static 'tienda/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'tienda/css/bootstrap.min.css' %}">
</head>
<body>

    {% block contenedor %}

    {% endblock %}

    {% if messages %}
        {% for message in messages %}

            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible" role="alert">
                <div>{{ message }}</div>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}

    <!-- JS include here -->
    <script src="{% static 'tienda/js/library.js' %}"></script>
    <script src="{% static 'tienda/js/bootstrap.bundle.min.js' %}"></script>
    <!-- fin - JS include -->
</body>
</html>

Django/sena/tienda/templates/tienda/index.html
{% extends 'tienda/base.html' %}

{% load static %}

{% block titul %} Inicio {% endblock %}

{% block contenedor %}

    <h1>Tienda SENA</h1>
    <div class="container text-center mb-5">
        <div class="row align-items-start">
            <div class="col col-3">
                <div class="list-group">
                    <a href="{% url 'tienda:index' %}?id=0" class="list-group-item list-group-item-action list-group-item-info {% if request.session.submenu == 0 %}active{% endif %}" aria-current="true">
                        Todos
                    </a>
                    {% for c in categorias %}
                        <a href="{% url 'tienda:index' %}?id={{ c.id }}" class="list-group-item list-group-item-action list-group-item-info {% if request.session.submenu == c.id %}active{% endif %}">{{ c.nombre }}</a>
                    {% endfor %}

                </div>
            </div>
            <div class="col col-9">
                <div class="card">
                    <h5 class="card-header">Productos</h5>
                    <div class="card-body">
                        {% for p in productos %}
                            {% if forloop.first %}
                                <div class="row mx-auto">
                            {% endif %}

                                <div class="card m-2" style="width: 18rem; float:left;">
                                    <img src="{{ p.foto.url }}" class="card-img-top" alt="...">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ p.nombre }} (${{ p.precio }})</h5>
                                        <p class="card-text text-sm text-muted">
                                            <figcaption class="blockquote-footer mt-1">
                                                <cite>Categoría: {{ p.categoria.nombre }}</cite>
                                            </figcaption>
                                        </p>
                                        {% if p.stock <= 0 %}
                                            <strong class="text-danger">Agotado!!</strong>
                                        {% else %}
                                            <form action="{% url 'tienda:carrito_agregar' %}" method="post">
                                                {% csrf_token %}
                                                    <input type="hidden" name="id" value="{{ p.id }}">
                                                    <input type="number" min="1" max="{{ p.stock }}" value="1" size="3" name="cantidad">
                                                    <button class="btn btn-outline-secondary">Add Carrito</button>
                                            </form>
                                        {% endif %}
                                    </div>
                                </div>

                            {% if forloop.counter|divisibleby:3 %}
                                </div>
                                <div class="row mx-auto">
                            {% endif %}

                            {% if forloop.last %}
                                </div>
                            {% endif %}


                        {% endfor %}



                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Django/sena/tienda/templates/tienda/login.html
{% extends 'tienda/base2.html' %}

{% load static %}

{% block titul %} Iniciar Sesion {% endblock %}

{% block contenedor %}

<div class="container pt-5 border col-md-12">
    <form class="" action="" method="post">
      {% csrf_token %}
      <div class="mb-3">
        <label for="username" class="form-label">Nombre de Usuario</label>
        <input type="text" class="form-control" id="username" aria-describedby="UserNameHelp" name="userName">
      </div>
      <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
      </div>
      <button type="submit" class="btn btn-outline-success mb-3">Submit</button>
    </form>
</div>

{% endblock %}

Django/sena/tienda/templates/tienda/logout.html
{% extends 'tienda/base.html' %}

{% load static %}

{% block titul %} Inicio {% endblock %}

{% block contenedor %}

<h1>Logout</h1>

{% endblock %}